//runtest.C is below.
//test.C and test.h are made by doing, ntp3->MakeClass(“test”)

Parallelized_script(){

gROOT->ProcessLine(".L MyClass.C+");

TChain *p1 = new TChain("trackTree","chain ChainTrackTree");

p1->Add(“file1.root”);
p1->Add(“file2.root”);

// run over the files
TTree* mytree = (TTree*)p1;
MyClass.C a(mytree);

a.Loop();

}



/*

TTree::MakeClass should be slightly modified  in case of a TChain.
You can, however, work with the code generated by MakeClass if you 
load the first event of the chain. In your case, the Root session could
be:

Root > .L bllac.C
Root > .L MyClass.C
Root > open_all("crab.root_list",...
Root > con->LoadTree(0); //this is the important line
Root > MyClass *ana = new MyClass(con)
Root > ana->Show(10);
Root > ana->Loop();

A better alternative is to add the following line in your MyClass.h file
in the function MyClass::Init, after the statement:
   if (tree == 0) return;
add the line
   if (tree->InheritsFrom("TChain")) ((TChain*)tree)->LoadTree(0);

Rene Brun


*/
